#!/bin/sh

STARTTIME=`date "+%s"`
echo 'Starting time: ' `date`
OPTS=

set -e

# Start: hello world js ------

# first build it from scratch
scc $OPTS -a -ta test.js.helloWorld  < test/scripts/wait10.txt

FULLENDTIME=`date "+%s"`
FULLTIME=`expr $FULLENDTIME - $STARTTIME`
echo 'Full hello world compile time: ' `date -j -f "%s" $FULLTIME "+%M:%S"`

touch test/js/helloWorld/helloWorld.schtml

# now do the incremental build 
scc $OPTS -ta test.js.helloWorld < test/scripts/wait10.txt

ENDTIME=`date "+%s"`
INCRTIME=`expr $ENDTIME - $FULLENDTIME`

# ------

RUNTIME=`expr $ENDTIME - $STARTTIME`

echo 'Incr time: ' `date -j -f "%s" $INCRTIME "+%M:%S"`
echo 'Run time: ' `date -j -f "%s" $RUNTIME "+%M:%S"`
echo 'Ending time: ' `date` 
