#!/bin/sh

STARTTIME=`date "+%s"`
echo 'Starting time: ' `date`

set -e

# Start: FormView/CodeView js-editor ------

# first build it from scratch
sc -a -ta editor.js.app editor/test/simpleModel < test/scripts/wait10.txt

FULLENDTIME=`date "+%s"`
FULLTIME=`expr $FULLENDTIME - $STARTTIME`
echo 'Full compile time: ' `date -j -f "%s" $FULLTIME "+%M:%S"`

touch editor/js/core/FormView.schtml
touch editor/js/core/CodeView.schtml
# now do the incremental build 
sc -ta editor.js.app editor/test/simpleModel < test/scripts/wait10.txt

ENDTIME=`date "+%s"`
INCRTIME=`expr $ENDTIME - $FULLENDTIME`

# ------

RUNTIME=`expr $ENDTIME - $STARTTIME`


echo 'Incr time: ' `date -j -f "%s" $INCRTIME "+%M:%S"`
echo 'Run time: ' `date -j -f "%s" $RUNTIME "+%M:%S"`
echo 'Ending time: ' `date` 
