#!/bin/sh

STARTTIME=`date "+%s"`
echo 'Starting time - incr unitConverter dynamic : ' `date`
OPTS=

set -e

# first build it from scratch
sc $OPTS -a -ta editor/js/mixin -dyn example/unitConverter/jsui  < test/scripts/wait10.txt

FULLENDTIME=`date "+%s"`
FULLTIME=`expr $FULLENDTIME - $STARTTIME`
echo 'Full unit converter compile time: ' `date -j -f "%s" $FULLTIME "+%M:%S"`

touch example/unitConverter/extendedModel/UnitConverter.sc

# now do the incremental build 
sc $OPTS -ta editor/js/mixin -dyn example/unitConverter/jsui < test/scripts/wait10.txt

ENDTIME=`date "+%s"`
INCRTIME=`expr $ENDTIME - $FULLENDTIME`

# ------

RUNTIME=`expr $ENDTIME - $STARTTIME`

echo 'Incr time: ' `date -j -f "%s" $INCRTIME "+%M:%S"`
echo 'Run time: ' `date -j -f "%s" $RUNTIME "+%M:%S"`
echo 'Ending time incr unit converter dynamic : ' `date` 
