#!/bin/sh

# This test can fail if the emptySwing/dynbuild directory gets a copy of Question.sc and Quiz.sc
# which are inherited.  The enhancer cannot find them.  Ultimately the enhancer should find the
# class file even if it's inherited... it should not assume a common build-dir

cp persist/QDM0.txt persist/QuizDataManager.sc

cp swing/PML0.txt swing/PopupMenuListener.sc

cp makequiz/MQ0.txt makequiz/MakeQuiz.sc
#cp makequiz/MQI1.txt makequiz/MakeQuizInit.sc
rm -f makequiz/MakeQuizInit.sc
cp makequiz/MQS0.txt makequiz/MakeQuizState.sc
cp makequiz/NQ0.txt makequiz/NameQuiz.sc
cp makequiz/QZL0.txt makequiz/QuizList.sc
cp makequiz/QTL0.txt makequiz/QuestionList.sc
cp makequiz/EQ0.txt makequiz/EditQuestion.sc

echo "Running refreshMQ"
scc -a . < script.txt

rm -f persist/QuizDataManager.sc swing/PopupMenuListener.sc makequiz/MakeQuiz.sc makequiz/MakeQuizInit.sc makequiz/MakeQuizState.sc makequiz/NameQuiz.sc makequiz/QuestionList.sc makequiz/EditQuestion.sc makequiz/QuizList.sc
