#!/bin/sh

cp model/QZ0.txt model/Quiz.sc
cp model/QT0.txt model/Question.sc
cp data/QD0.txt data/QuizData.sc

cp takequiz/TQM0.txt takequiz/TakeQuizMain.sc
cp takequiz/TQ0.txt takequiz/TakeQuiz.sc

echo "Running refreshQuiz"
sc -a . < script.txt

rm model/Quiz.sc model/Question.sc data/QuizData.sc takequiz/TakeQuizMain.sc takequiz/Takequiz.sc
