#!/bin/sh

echo 'Running demo: ' `date`
set -e

STARTTIME=`date "+%s"`

scc -ta editor/js/mixin -dyn example/unitConverter/jsui < test/scripts/wait20.txt
scc -ta -ni example/todo/clientOnly
scc -ta -ee -dyn editor/js/mixin example/todo/clientServer < test/scripts/wait20.txt
scc -ta example/todo/clientServer editor/js/options/windowScope < test/scripts/wait20.txt

ENDTIME=`date "+%s"`
RUNTIME=`expr $ENDTIME - $STARTTIME`

echo 'Demo tests: incr startup run time: ' `date -j -f "%s" $RUNTIME "+%M:%S"`
