#!/bin/sh

echo 'Running demo: ' `date`
set -e

STARTTIME=`date "+%s"`

sc -ta editor/js/mixin -dyn unitConverter/jsui < test/scripts/wait10.txt
sc -ta -ni example/todo/clientOnly
sc -ta -ee -dyn editor/js/mixin example/todo/clientServer < test/scripts/wait10.txt
sc -ta example/todo/clientServer editor/js/options/windowScope < test/scripts/wait10.txt

ENDTIME=`date "+%s"`
RUNTIME=`expr $ENDTIME - $STARTTIME`

echo 'Demo tests: incr startup run time: ' `date -j -f "%s" $RUNTIME "+%M:%S"`
