#!/bin/sh

set -e

echo "------- Running tests: incr/runHelloWorld"
./test/scripts/incr/runHelloWorld

echo "------- Running tests: incr/runUnitConverter"
./test/scripts/incr/runUnitConverter

echo "------- Running tests: incr/runJSEditor"
./test/scripts/incr/runJSEditor

echo "------- Running tests: incr/runTodo"
./test/scripts/incr/runTodo

echo "------- Running tests: incr/runTodo with Mixin"
./test/scripts/incr/runTodo editor/js/mixin

echo "------- Running tests: incr/switchModes"
./test/scripts/incr/switchModes

echo "------- Running tests: incr/todoDynFail"
./test/scripts/incr/todoDynFail
