#!/bin/sh


java -version 2>&1 | grep "\"1\.8\."
if [ "$?" = "1" ] ; then
  echo "Skipping Java8 tests"
  exit 0
fi

set -e

scc -a -ni -ta test/lambda
scc -a -ni -ta -cc test/lambda

scc -a -ni -ta test/java7Misc
scc -a -ni -ta -cc test/java7Misc

scc -a -ni -ta js/allInOne/main test/java7Misc 
scc -a -ni -ta -cc js/allInOne/main test/java7Misc 

scc -a -ni -ta test/java7Thread
scc -a -ni -ta -cc test/java7Thread

scc -a -ni -ta test/defaultMethods
scc -a -ni -ta -cc test/defaultMethods

scc -a example/quiz/wicket/makequiz < wicket/bookExamp/script.txt -i -r sc.jetty.CServer
scc -a -dynone example/quiz/wicket/makequiz < wicket/bookExamp/script.txt -i -r sc.jetty.CServer

scc -a editor/swing/threeD editor/swing/vim example/expertSystem/swingui  < test/scripts/editorScript.txt
scc -a -cc editor/swing/threeD editor/swing/vim example/expertSystem/swingui  < test/scripts/editorScript.txt

scc -a -dyn editor/swing/threeD editor/swing/vim example/expertSystem/swingui < test/scripts/editorScript.txt
scc -a -cc -dyn editor/swing/threeD editor/swing/vim example/expertSystem/swingui < test/scripts/editorScript.txt

(cd test/refreshMQ; ./run)

(cd test/wicketMQ; ./run)

scc -a -ni -ta test/jool
scc -a -ni -ta -cc test/jool 

scc -a -ta spring/example/petclinic < test/scripts/wait20.txt
