#!/bin/sh

set -e

scc -ni -a -ta test/ifaceField/ibase
scc -ni -a -ta test/ifaceField/ibind

scc -ni -a test/componentInner

scc -ni -dynone -a -ta test/ifaceField/ibase
scc -ni -dynone -a -ta test/ifaceField/ibind

sh test/scripts/run-compiled-demo


rm -rf unitDemo
rm -rf temp/build/unitDemo_*
scc < test/scripts/ds-swingui2.txt

scc -a test/emptySwing -i < example/unitConverter/test/buildScript.txt -r sc.swing.Main

#  Annoying tests that pop up lots of windows

(cd test/wicketUC; ./run)

(cd test/wicketQuiz; ./run)

rm -rf unitDemo
