#!/bin/sh

ARG=

set -e
scc -a -ta $ARG spring/example/petclinic < test/scripts/wait20.txt
scc -a -ta $ARG test/petclinic < test/scripts/wait20.txt
scc -a -ta $ARG -ni ticketmonster/core
scc -a -ta $ARG -ni broadleaf/core
scc -a -ta $ARG -ni killbill/core


