#!/bin/sh

set -e

rm -rf unitDemo
rm -rf .stratacode/build/unitDemo_*
rm -rf .stratacode/dynbuild/unitDemo_*
scc < test/scripts/ds2-script.txt

sh test/scripts/run-all-compiled-demo

# NOTE: Something that compiles the sc.servlet.tag library must be compiled before the doc

# The documentation 
scc -a doc.core < test/scripts/wait10.txt

scc -ni -a test/multiComponentTest/subsub

# Run with just GetSet interpreted
scc -ni -a -dynone test.GetSet  -t "sc.*"
# Run with both GetSet and GetSetBase interpreted
scc -ni -a -dynone test.GetSetBase test.GetSet -t "sc.*"
# Run compiled
scc -ni -a test.GetSet -t "sc.*"
scc -ni -a -dynone test.simpleBinding -r "sc.*"
scc -ni -a test.simpleBinding -r "sc.*"
scc -ni -a -ta test.innerLevels
scc -dyn -a -ni -ta test.innerLevels

scc -ni -a test/langTest
scc -ni -a -dyn test/langTest

# Tests mixed compiled/dynamic modes
scc -ni -a test/dyn -r "test.*"


# Runs the older version of the editor just to increase code-coverage since there were lots of changes
scc -a test/editor/swing/main example/expertSystem/swingui  < test/scripts/editorScript.txt
scc -a -dyn test/editor/swing/main example/expertSystem/swingui < test/scripts/editorScript.txt


rm -rf unitDemo

