#!/bin/sh

set -e

rm -rf unitDemo
rm -rf .stratacode/build/unitDemo_*
rm -rf .stratacode/dynbuild/unitDemo_*
sc < test/scripts/ds2-script.txt

sh test/scripts/run-all-compiled-demo

# NOTE: Something that compiles the sc.servlet.tag library must be compiled before the doc

# The documentation 
sc -a doc.core < test/scripts/wait10.txt

sc -ni -a test/multiComponentTest/subsub

# Run with just GetSet interpreted
sc -ni -a -dynone test.GetSet  -t "sc.*"
# Run with both GetSet and GetSetBase interpreted
sc -ni -a -dynone test.GetSetBase test.GetSet -t "sc.*"
# Run compiled
sc -ni -a test.GetSet -t "sc.*"
sc -ni -a -dynone test.simpleBinding -r "sc.*"
sc -ni -a test.simpleBinding -r "sc.*"
sc -ni -a -ta test.innerLevels
sc -dyn -a -ni -ta test.innerLevels

# Tests mixed compiled/dynamic modes
sc -ni -a test/dyn -r "test.*"



rm -rf unitDemo

