#!/bin/csh

cd ..

set verbose
#
# Compile only
#
#ccake -a catTest/jpaCat 
#

# 1000k cache
#set baseTest="catTest/cfg/wideTest catTest/cfg/onekcache"
# 100 cache
#set baseTest="catTest/cfg/wideTest catTest/cfg/onehcache"
# 100,000 cache
set baseTest="catTest/cfg/wideTest" 
# 1,000,000
set baseTest="catTest/cfg/wideTest catTest/cfg/onemcache" 

#
# Run the tests
#

ccake -a catTest/jpaCat $baseTest catTest/cfg/shortTest -rs "jpaCat.JPACatalogManager" >&! catTest/logs/openjpa.short
ccake -a catTest/jpaCat $baseTest  -rs "jpaCat.JPACatalogManager" >&! catTest/logs/openjpa.normal
ccake -a catTest/jpaCat $baseTest catTest/cfg/replay -rs "jpaCat.JPACatalogManager" >&! catTest/logs/openjpa.replay

ccake -a catTest/hibCat $baseTest catTest/cfg/shortTest -rs "jpaCat.JPACatalogManager" >&! catTest/logs/hib.short
ccake -a catTest/hibCat $baseTest -rs "jpaCat.JPACatalogManager" >&! catTest/logs/hib.normal
ccake -a catTest/hibCat $baseTest catTest/cfg/replay -rs "jpaCat.JPACatalogManager" >&! catTest/logs/hib.replay

catTest/runReposTest catTest/reposCat $baseTest catTest/cfg/shortTest >&! catTest/logs/repos.short
catTest/runReposTest catTest/reposCat catTest/cfg/wideTest >&! catTest/logs/repos.normal
catTest/runReposTest catTest/reposCat catTest/cfg/wideTest catTest/cfg/replay >&! catTest/logs/repos.replay
